/**
 * Ambient declaration for the OpenNext build artifact.
 *
 * `.open-next/worker.js` is generated by `npm run cf:build` and does not exist
 * in a clean checkout. Declaring it here keeps `src/worker.ts` type-checking
 * both before and after a build — a `@ts-expect-error` would flip to "unused
 * directive" once the artifact appears.
 */
declare module "*/.open-next/worker.js" {
  const handler: ExportedHandler<Env>;
  export default handler;

  // Durable Object classes re-exported by the generated worker.
  export const DOQueueHandler: unknown;
  export const DOShardedTagCache: unknown;
  export const BucketCachePurge: unknown;
}
