// BLUEPRINT §12.3 — cron keep-alive.
//
// OpenNext has no cron of its own, but the Worker it produces supports
// Cloudflare Cron Triggers, and OpenNext lets us attach a custom scheduled()
// handler alongside the Next.js fetch handler. We WRAP the generated handler
// rather than replacing it, so Next.js SSR keeps working.
//
// `Env` is a global generated by `wrangler types` into worker-configuration.d.ts;
// re-run `npm run cf:typegen` after changing wrangler.toml.
//
// `.open-next/worker.js` is a build artifact produced by `npm run cf:build`.
// Its shape is declared ambiently in src/open-next-worker.d.ts.
import handler from "../.open-next/worker.js";

export default {
  fetch: handler.fetch,

  async scheduled(
    _event: ScheduledController,
    env: Env,
    ctx: ExecutionContext,
  ) {
    // waitUntil so the Worker is not torn down before the request settles.
    ctx.waitUntil(
      fetch(env.API_HEALTH_URL, {
        method: "GET",
        headers: { "user-agent": "zoom-clone-keepalive/1.0" },
      })
        .then((r) => console.log(`keepalive ${r.status}`))
        .catch((e) => console.error("keepalive failed", e)),
    );
  },
} satisfies ExportedHandler<Env>;

// The generated worker also exports Durable Object classes (DOQueueHandler,
// DOShardedTagCache, BucketCachePurge). Re-export them so bindings that
// reference those class names still resolve through this wrapper.
export * from "../.open-next/worker.js";
